### ISSUE TITLE
ScreenShotError: $DISPLAY not set.

### ISSUE THREAD

**Issue by cccarv** [mihaiparvu/ScreenCapLibrary#70]
General information:

* OS name: Linux Ubuntu
* OS version: latest version
* OS architecture: 64 bits
* Python version: 3.7

I'm trying to implement screenshot captures to my Appium Robot Framework tests but i'm getting this error:

`ScreenShotError: $DISPLAY not set.`

Code example:
```
***Settings***

Library         AppiumLibrary
Library         ScreenCapLibrary

***Keywords***
Validate Screen
    Wait Until Element Is Visible           id=com.anything.qa:id/test_id
    Take Screenshot                             name=screenshot     format=jpg
```

Aditional Information:
I'm using Azure DevOps Pipeline to run my code. Some settings:
```
pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'
- task: CmdLine@2
  inputs:
    script: 'pip install robotframework robotframework-appiumlibrary robotframework-screencaplibrary'
  displayName: 'Robot Install'
```
